/*
 * generated by Xtext 2.33.0
 */
package org.xtext.example.mydsl.ui.tests;

import com.google.inject.Injector;
import mongoDBDSL.ui.internal.MongoDBDSLActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class MyDslUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return MongoDBDSLActivator.getInstance().getInjector("org.xtext.example.mydsl.MyDsl");
	}

}
