/**
 * generated by Xtext 2.33.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Collection</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Collection#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Collection#getFields <em>Fields</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Collection#getIndexes <em>Indexes</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Collection#getSeedData <em>Seed Data</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getCollection()
 * @model
 * @generated
 */
public interface Collection extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getCollection_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Collection#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Fields</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.myDsl.Field}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Fields</em>' containment reference list.
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getCollection_Fields()
   * @model containment="true"
   * @generated
   */
  EList<Field> getFields();

  /**
   * Returns the value of the '<em><b>Indexes</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.myDsl.Index}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Indexes</em>' containment reference list.
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getCollection_Indexes()
   * @model containment="true"
   * @generated
   */
  EList<Index> getIndexes();

  /**
   * Returns the value of the '<em><b>Seed Data</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Seed Data</em>' containment reference.
   * @see #setSeedData(SeedData)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getCollection_SeedData()
   * @model containment="true"
   * @generated
   */
  SeedData getSeedData();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Collection#getSeedData <em>Seed Data</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Seed Data</em>' containment reference.
   * @see #getSeedData()
   * @generated
   */
  void setSeedData(SeedData value);

} // Collection
