/**
 * generated by Xtext 2.33.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Data Value</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.DataValue#getStringValue <em>String Value</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.DataValue#getIntValue <em>Int Value</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.DataValue#getDoubleValue <em>Double Value</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.DataValue#getBooleanValue <em>Boolean Value</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getDataValue()
 * @model
 * @generated
 */
public interface DataValue extends EObject
{
  /**
   * Returns the value of the '<em><b>String Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>String Value</em>' attribute.
   * @see #setStringValue(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getDataValue_StringValue()
   * @model
   * @generated
   */
  String getStringValue();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.DataValue#getStringValue <em>String Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>String Value</em>' attribute.
   * @see #getStringValue()
   * @generated
   */
  void setStringValue(String value);

  /**
   * Returns the value of the '<em><b>Int Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Int Value</em>' attribute.
   * @see #setIntValue(int)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getDataValue_IntValue()
   * @model
   * @generated
   */
  int getIntValue();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.DataValue#getIntValue <em>Int Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Int Value</em>' attribute.
   * @see #getIntValue()
   * @generated
   */
  void setIntValue(int value);

  /**
   * Returns the value of the '<em><b>Double Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Double Value</em>' attribute.
   * @see #setDoubleValue(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getDataValue_DoubleValue()
   * @model
   * @generated
   */
  String getDoubleValue();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.DataValue#getDoubleValue <em>Double Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Double Value</em>' attribute.
   * @see #getDoubleValue()
   * @generated
   */
  void setDoubleValue(String value);

  /**
   * Returns the value of the '<em><b>Boolean Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Boolean Value</em>' attribute.
   * @see #setBooleanValue(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getDataValue_BooleanValue()
   * @model
   * @generated
   */
  String getBooleanValue();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.DataValue#getBooleanValue <em>Boolean Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Boolean Value</em>' attribute.
   * @see #getBooleanValue()
   * @generated
   */
  void setBooleanValue(String value);

} // DataValue
