/**
 * generated by Xtext 2.33.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>DB Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.DBModel#getCollections <em>Collections</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getDBModel()
 * @model
 * @generated
 */
public interface DBModel extends EObject
{
  /**
   * Returns the value of the '<em><b>Collections</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.myDsl.Collection}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Collections</em>' containment reference list.
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getDBModel_Collections()
   * @model containment="true"
   * @generated
   */
  EList<Collection> getCollections();

} // DBModel
