/**
 * generated by Xtext 2.33.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.example.mydsl.myDsl.MyDslFactory
 * @model kind="package"
 * @generated
 */
public interface MyDslPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "myDsl";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/example/mydsl/MyDsl";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "myDsl";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  MyDslPackage eINSTANCE = org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.DBModelImpl <em>DB Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.DBModelImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getDBModel()
   * @generated
   */
  int DB_MODEL = 0;

  /**
   * The feature id for the '<em><b>Collections</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DB_MODEL__COLLECTIONS = 0;

  /**
   * The number of structural features of the '<em>DB Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DB_MODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.CollectionImpl <em>Collection</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.CollectionImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getCollection()
   * @generated
   */
  int COLLECTION = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLLECTION__NAME = 0;

  /**
   * The feature id for the '<em><b>Fields</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLLECTION__FIELDS = 1;

  /**
   * The feature id for the '<em><b>Indexes</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLLECTION__INDEXES = 2;

  /**
   * The feature id for the '<em><b>Seed Data</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLLECTION__SEED_DATA = 3;

  /**
   * The number of structural features of the '<em>Collection</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLLECTION_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.FieldImpl <em>Field</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.FieldImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getField()
   * @generated
   */
  int FIELD = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FIELD__NAME = 0;

  /**
   * The feature id for the '<em><b>Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FIELD__TYPE = 1;

  /**
   * The number of structural features of the '<em>Field</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FIELD_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.DataTypeImpl <em>Data Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.DataTypeImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getDataType()
   * @generated
   */
  int DATA_TYPE = 3;

  /**
   * The feature id for the '<em><b>Data Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATA_TYPE__DATA_TYPE = 0;

  /**
   * The number of structural features of the '<em>Data Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATA_TYPE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.IndexImpl <em>Index</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.IndexImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getIndex()
   * @generated
   */
  int INDEX = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INDEX__NAME = 0;

  /**
   * The feature id for the '<em><b>Fields</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INDEX__FIELDS = 1;

  /**
   * The number of structural features of the '<em>Index</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INDEX_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.SeedDataImpl <em>Seed Data</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.SeedDataImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getSeedData()
   * @generated
   */
  int SEED_DATA = 5;

  /**
   * The feature id for the '<em><b>Collection Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SEED_DATA__COLLECTION_NAME = 0;

  /**
   * The feature id for the '<em><b>Data Arrays</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SEED_DATA__DATA_ARRAYS = 1;

  /**
   * The number of structural features of the '<em>Seed Data</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SEED_DATA_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.DataArrayImpl <em>Data Array</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.DataArrayImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getDataArray()
   * @generated
   */
  int DATA_ARRAY = 6;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATA_ARRAY__NAME = 0;

  /**
   * The feature id for the '<em><b>Data Pairs</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATA_ARRAY__DATA_PAIRS = 1;

  /**
   * The number of structural features of the '<em>Data Array</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATA_ARRAY_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.DataPairImpl <em>Data Pair</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.DataPairImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getDataPair()
   * @generated
   */
  int DATA_PAIR = 7;

  /**
   * The feature id for the '<em><b>Field Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATA_PAIR__FIELD_NAME = 0;

  /**
   * The feature id for the '<em><b>Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATA_PAIR__VALUE = 1;

  /**
   * The feature id for the '<em><b>Data Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATA_PAIR__DATA_TYPE = 2;

  /**
   * The number of structural features of the '<em>Data Pair</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATA_PAIR_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.DataValueImpl <em>Data Value</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.DataValueImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getDataValue()
   * @generated
   */
  int DATA_VALUE = 8;

  /**
   * The feature id for the '<em><b>String Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATA_VALUE__STRING_VALUE = 0;

  /**
   * The feature id for the '<em><b>Int Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATA_VALUE__INT_VALUE = 1;

  /**
   * The feature id for the '<em><b>Double Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATA_VALUE__DOUBLE_VALUE = 2;

  /**
   * The feature id for the '<em><b>Boolean Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATA_VALUE__BOOLEAN_VALUE = 3;

  /**
   * The number of structural features of the '<em>Data Value</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATA_VALUE_FEATURE_COUNT = 4;


  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.DBModel <em>DB Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>DB Model</em>'.
   * @see org.xtext.example.mydsl.myDsl.DBModel
   * @generated
   */
  EClass getDBModel();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.myDsl.DBModel#getCollections <em>Collections</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Collections</em>'.
   * @see org.xtext.example.mydsl.myDsl.DBModel#getCollections()
   * @see #getDBModel()
   * @generated
   */
  EReference getDBModel_Collections();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Collection <em>Collection</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Collection</em>'.
   * @see org.xtext.example.mydsl.myDsl.Collection
   * @generated
   */
  EClass getCollection();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Collection#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.myDsl.Collection#getName()
   * @see #getCollection()
   * @generated
   */
  EAttribute getCollection_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.myDsl.Collection#getFields <em>Fields</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Fields</em>'.
   * @see org.xtext.example.mydsl.myDsl.Collection#getFields()
   * @see #getCollection()
   * @generated
   */
  EReference getCollection_Fields();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.myDsl.Collection#getIndexes <em>Indexes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Indexes</em>'.
   * @see org.xtext.example.mydsl.myDsl.Collection#getIndexes()
   * @see #getCollection()
   * @generated
   */
  EReference getCollection_Indexes();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.Collection#getSeedData <em>Seed Data</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Seed Data</em>'.
   * @see org.xtext.example.mydsl.myDsl.Collection#getSeedData()
   * @see #getCollection()
   * @generated
   */
  EReference getCollection_SeedData();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Field <em>Field</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Field</em>'.
   * @see org.xtext.example.mydsl.myDsl.Field
   * @generated
   */
  EClass getField();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Field#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.myDsl.Field#getName()
   * @see #getField()
   * @generated
   */
  EAttribute getField_Name();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.Field#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Type</em>'.
   * @see org.xtext.example.mydsl.myDsl.Field#getType()
   * @see #getField()
   * @generated
   */
  EReference getField_Type();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.DataType <em>Data Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Data Type</em>'.
   * @see org.xtext.example.mydsl.myDsl.DataType
   * @generated
   */
  EClass getDataType();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.DataType#getDataType <em>Data Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Data Type</em>'.
   * @see org.xtext.example.mydsl.myDsl.DataType#getDataType()
   * @see #getDataType()
   * @generated
   */
  EReference getDataType_DataType();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Index <em>Index</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Index</em>'.
   * @see org.xtext.example.mydsl.myDsl.Index
   * @generated
   */
  EClass getIndex();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Index#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.myDsl.Index#getName()
   * @see #getIndex()
   * @generated
   */
  EAttribute getIndex_Name();

  /**
   * Returns the meta object for the attribute list '{@link org.xtext.example.mydsl.myDsl.Index#getFields <em>Fields</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Fields</em>'.
   * @see org.xtext.example.mydsl.myDsl.Index#getFields()
   * @see #getIndex()
   * @generated
   */
  EAttribute getIndex_Fields();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.SeedData <em>Seed Data</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Seed Data</em>'.
   * @see org.xtext.example.mydsl.myDsl.SeedData
   * @generated
   */
  EClass getSeedData();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.SeedData#getCollectionName <em>Collection Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Collection Name</em>'.
   * @see org.xtext.example.mydsl.myDsl.SeedData#getCollectionName()
   * @see #getSeedData()
   * @generated
   */
  EAttribute getSeedData_CollectionName();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.myDsl.SeedData#getDataArrays <em>Data Arrays</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Data Arrays</em>'.
   * @see org.xtext.example.mydsl.myDsl.SeedData#getDataArrays()
   * @see #getSeedData()
   * @generated
   */
  EReference getSeedData_DataArrays();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.DataArray <em>Data Array</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Data Array</em>'.
   * @see org.xtext.example.mydsl.myDsl.DataArray
   * @generated
   */
  EClass getDataArray();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.DataArray#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.myDsl.DataArray#getName()
   * @see #getDataArray()
   * @generated
   */
  EAttribute getDataArray_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.myDsl.DataArray#getDataPairs <em>Data Pairs</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Data Pairs</em>'.
   * @see org.xtext.example.mydsl.myDsl.DataArray#getDataPairs()
   * @see #getDataArray()
   * @generated
   */
  EReference getDataArray_DataPairs();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.DataPair <em>Data Pair</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Data Pair</em>'.
   * @see org.xtext.example.mydsl.myDsl.DataPair
   * @generated
   */
  EClass getDataPair();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.DataPair#getFieldName <em>Field Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Field Name</em>'.
   * @see org.xtext.example.mydsl.myDsl.DataPair#getFieldName()
   * @see #getDataPair()
   * @generated
   */
  EAttribute getDataPair_FieldName();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.DataPair#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Value</em>'.
   * @see org.xtext.example.mydsl.myDsl.DataPair#getValue()
   * @see #getDataPair()
   * @generated
   */
  EReference getDataPair_Value();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.DataPair#getDataType <em>Data Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Data Type</em>'.
   * @see org.xtext.example.mydsl.myDsl.DataPair#getDataType()
   * @see #getDataPair()
   * @generated
   */
  EReference getDataPair_DataType();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.DataValue <em>Data Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Data Value</em>'.
   * @see org.xtext.example.mydsl.myDsl.DataValue
   * @generated
   */
  EClass getDataValue();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.DataValue#getStringValue <em>String Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>String Value</em>'.
   * @see org.xtext.example.mydsl.myDsl.DataValue#getStringValue()
   * @see #getDataValue()
   * @generated
   */
  EAttribute getDataValue_StringValue();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.DataValue#getIntValue <em>Int Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Int Value</em>'.
   * @see org.xtext.example.mydsl.myDsl.DataValue#getIntValue()
   * @see #getDataValue()
   * @generated
   */
  EAttribute getDataValue_IntValue();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.DataValue#getDoubleValue <em>Double Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Double Value</em>'.
   * @see org.xtext.example.mydsl.myDsl.DataValue#getDoubleValue()
   * @see #getDataValue()
   * @generated
   */
  EAttribute getDataValue_DoubleValue();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.DataValue#getBooleanValue <em>Boolean Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Boolean Value</em>'.
   * @see org.xtext.example.mydsl.myDsl.DataValue#getBooleanValue()
   * @see #getDataValue()
   * @generated
   */
  EAttribute getDataValue_BooleanValue();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  MyDslFactory getMyDslFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.DBModelImpl <em>DB Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.DBModelImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getDBModel()
     * @generated
     */
    EClass DB_MODEL = eINSTANCE.getDBModel();

    /**
     * The meta object literal for the '<em><b>Collections</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DB_MODEL__COLLECTIONS = eINSTANCE.getDBModel_Collections();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.CollectionImpl <em>Collection</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.CollectionImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getCollection()
     * @generated
     */
    EClass COLLECTION = eINSTANCE.getCollection();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COLLECTION__NAME = eINSTANCE.getCollection_Name();

    /**
     * The meta object literal for the '<em><b>Fields</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COLLECTION__FIELDS = eINSTANCE.getCollection_Fields();

    /**
     * The meta object literal for the '<em><b>Indexes</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COLLECTION__INDEXES = eINSTANCE.getCollection_Indexes();

    /**
     * The meta object literal for the '<em><b>Seed Data</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COLLECTION__SEED_DATA = eINSTANCE.getCollection_SeedData();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.FieldImpl <em>Field</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.FieldImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getField()
     * @generated
     */
    EClass FIELD = eINSTANCE.getField();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FIELD__NAME = eINSTANCE.getField_Name();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FIELD__TYPE = eINSTANCE.getField_Type();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.DataTypeImpl <em>Data Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.DataTypeImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getDataType()
     * @generated
     */
    EClass DATA_TYPE = eINSTANCE.getDataType();

    /**
     * The meta object literal for the '<em><b>Data Type</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DATA_TYPE__DATA_TYPE = eINSTANCE.getDataType_DataType();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.IndexImpl <em>Index</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.IndexImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getIndex()
     * @generated
     */
    EClass INDEX = eINSTANCE.getIndex();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INDEX__NAME = eINSTANCE.getIndex_Name();

    /**
     * The meta object literal for the '<em><b>Fields</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INDEX__FIELDS = eINSTANCE.getIndex_Fields();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.SeedDataImpl <em>Seed Data</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.SeedDataImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getSeedData()
     * @generated
     */
    EClass SEED_DATA = eINSTANCE.getSeedData();

    /**
     * The meta object literal for the '<em><b>Collection Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SEED_DATA__COLLECTION_NAME = eINSTANCE.getSeedData_CollectionName();

    /**
     * The meta object literal for the '<em><b>Data Arrays</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SEED_DATA__DATA_ARRAYS = eINSTANCE.getSeedData_DataArrays();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.DataArrayImpl <em>Data Array</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.DataArrayImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getDataArray()
     * @generated
     */
    EClass DATA_ARRAY = eINSTANCE.getDataArray();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DATA_ARRAY__NAME = eINSTANCE.getDataArray_Name();

    /**
     * The meta object literal for the '<em><b>Data Pairs</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DATA_ARRAY__DATA_PAIRS = eINSTANCE.getDataArray_DataPairs();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.DataPairImpl <em>Data Pair</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.DataPairImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getDataPair()
     * @generated
     */
    EClass DATA_PAIR = eINSTANCE.getDataPair();

    /**
     * The meta object literal for the '<em><b>Field Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DATA_PAIR__FIELD_NAME = eINSTANCE.getDataPair_FieldName();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DATA_PAIR__VALUE = eINSTANCE.getDataPair_Value();

    /**
     * The meta object literal for the '<em><b>Data Type</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DATA_PAIR__DATA_TYPE = eINSTANCE.getDataPair_DataType();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.DataValueImpl <em>Data Value</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.DataValueImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getDataValue()
     * @generated
     */
    EClass DATA_VALUE = eINSTANCE.getDataValue();

    /**
     * The meta object literal for the '<em><b>String Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DATA_VALUE__STRING_VALUE = eINSTANCE.getDataValue_StringValue();

    /**
     * The meta object literal for the '<em><b>Int Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DATA_VALUE__INT_VALUE = eINSTANCE.getDataValue_IntValue();

    /**
     * The meta object literal for the '<em><b>Double Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DATA_VALUE__DOUBLE_VALUE = eINSTANCE.getDataValue_DoubleValue();

    /**
     * The meta object literal for the '<em><b>Boolean Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DATA_VALUE__BOOLEAN_VALUE = eINSTANCE.getDataValue_BooleanValue();

  }

} //MyDslPackage
