/**
 * generated by Xtext 2.33.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Seed Data</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.SeedData#getCollectionName <em>Collection Name</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.SeedData#getDataArrays <em>Data Arrays</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getSeedData()
 * @model
 * @generated
 */
public interface SeedData extends EObject
{
  /**
   * Returns the value of the '<em><b>Collection Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Collection Name</em>' attribute.
   * @see #setCollectionName(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getSeedData_CollectionName()
   * @model
   * @generated
   */
  String getCollectionName();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.SeedData#getCollectionName <em>Collection Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Collection Name</em>' attribute.
   * @see #getCollectionName()
   * @generated
   */
  void setCollectionName(String value);

  /**
   * Returns the value of the '<em><b>Data Arrays</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.myDsl.DataArray}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Data Arrays</em>' containment reference list.
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getSeedData_DataArrays()
   * @model containment="true"
   * @generated
   */
  EList<DataArray> getDataArrays();

} // SeedData
