/*
 * generated by Xtext 2.33.0
 */
package org.xtext.example.mydsl.serializer;

import com.google.inject.Inject;
import java.util.List;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.IGrammarAccess;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.nodemodel.INode;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AbstractElementAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AlternativeAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.TokenAlias;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynNavigable;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynTransition;
import org.eclipse.xtext.serializer.sequencer.AbstractSyntacticSequencer;
import org.xtext.example.mydsl.services.MyDslGrammarAccess;

@SuppressWarnings("all")
public class MyDslSyntacticSequencer extends AbstractSyntacticSequencer {

	protected MyDslGrammarAccess grammarAccess;
	protected AbstractElementAlias match_DataType_BooleanKeyword_2_1_or_DateKeyword_3_1_or_NumberKeyword_1_1_or_ObjectIdKeyword_6_1_or_ObjectKeyword_4_1_or_StringKeyword_0_1;
	
	@Inject
	protected void init(IGrammarAccess access) {
		grammarAccess = (MyDslGrammarAccess) access;
		match_DataType_BooleanKeyword_2_1_or_DateKeyword_3_1_or_NumberKeyword_1_1_or_ObjectIdKeyword_6_1_or_ObjectKeyword_4_1_or_StringKeyword_0_1 = new AlternativeAlias(false, false, new TokenAlias(false, false, grammarAccess.getDataTypeAccess().getBooleanKeyword_2_1()), new TokenAlias(false, false, grammarAccess.getDataTypeAccess().getDateKeyword_3_1()), new TokenAlias(false, false, grammarAccess.getDataTypeAccess().getNumberKeyword_1_1()), new TokenAlias(false, false, grammarAccess.getDataTypeAccess().getObjectIdKeyword_6_1()), new TokenAlias(false, false, grammarAccess.getDataTypeAccess().getObjectKeyword_4_1()), new TokenAlias(false, false, grammarAccess.getDataTypeAccess().getStringKeyword_0_1()));
	}
	
	@Override
	protected String getUnassignedRuleCallToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		return "";
	}
	
	
	@Override
	protected void emitUnassignedTokens(EObject semanticObject, ISynTransition transition, INode fromNode, INode toNode) {
		if (transition.getAmbiguousSyntaxes().isEmpty()) return;
		List<INode> transitionNodes = collectNodes(fromNode, toNode);
		for (AbstractElementAlias syntax : transition.getAmbiguousSyntaxes()) {
			List<INode> syntaxNodes = getNodesFor(transitionNodes, syntax);
			if (match_DataType_BooleanKeyword_2_1_or_DateKeyword_3_1_or_NumberKeyword_1_1_or_ObjectIdKeyword_6_1_or_ObjectKeyword_4_1_or_StringKeyword_0_1.equals(syntax))
				emit_DataType_BooleanKeyword_2_1_or_DateKeyword_3_1_or_NumberKeyword_1_1_or_ObjectIdKeyword_6_1_or_ObjectKeyword_4_1_or_StringKeyword_0_1(semanticObject, getLastNavigableState(), syntaxNodes);
			else acceptNodes(getLastNavigableState(), syntaxNodes);
		}
	}

	/**
	 * <pre>
	 * Ambiguous syntax:
	 *     (
	  *         'String' | 
	  *         'Number' | 
	  *         'Boolean' | 
	  *         'Date' | 
	  *         'Object' | 
	  *         'ObjectId'
	  *     )
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (ambiguity) (rule start)
	 
	 * </pre>
	 */
	protected void emit_DataType_BooleanKeyword_2_1_or_DateKeyword_3_1_or_NumberKeyword_1_1_or_ObjectIdKeyword_6_1_or_ObjectKeyword_4_1_or_StringKeyword_0_1(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
}
